# Generated by Django 4.2.6 on 2023-11-01 06:50

from django.db import migrations, models
import django.db.models.deletion
import drfecommerce.apps.product.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("alternative_text", models.CharField(max_length=255)),
                ("url", models.ImageField(upload_to="")),
                ("order", drfecommerce.apps.product.fields.OrderField(blank=True)),
                (
                    "productline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image",
                        to="product.productline",
                    ),
                ),
            ],
        ),
    ]
