# Generated by Django 4.2.6 on 2023-11-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.ImageField(default="test.jpg", upload_to=None),
        ),
    ]
